# Workflow name
name: 'Chromatic packages/ui'

# Event for the workflow
on:
  pull_request:
    types: [opened, synchronize]
    branches-ignore:
      - 'renovate/**'
      - 'dependabot/**'

# List of jobs
jobs:
  chromatic-deployment:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn
        # 👇 Adds Chromatic as a step in the workflow
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        # Chromatic GitHub Action options
        with:
          # 👇 Chromatic projectToken, refer to the manage page to obtain it.
          projectToken: ${{ secrets.CHROMATIC_SITES_UI }}
          workingDir: packages/ui
